apiVersion: v1
kind: Service
metadata:
  name: httpbin-issue-2
  labels:
    app: httpbin-issue-2
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: httpbin-issue-2
    version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-issue-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-issue-2
      version: v2
  template:
    metadata:
      labels:
        app: httpbin-issue-2
        version: v2
    spec:
      containers:
      - image: docker.io/citizenstig/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 8000
