apiVersion: v1
kind: Service
metadata:
  name: httpbin-issue-7
  labels:
    app: httpbin-issue-7
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: httpbin-issue-7
    version: v7
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-issue-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-issue-7
      version: v7
  template:
    metadata:
      labels:
        app: httpbin-issue-7
        version: v7
    spec:
      containers:
      - image: docker.io/citizenstig/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpbin-issue-7-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: httpbin-issue-7
          servicePort: 8000
