apiVersion: v1
kind: Service
metadata:
  name: httpbin-issue-4
  labels:
    app: httpbin-issue-4
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: httpbin-issue-4
    version: v4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-issue-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-issue-4
      version: v4
  template:
    metadata:
      labels:
        app: httpbin-issue-4
        version: v4
    spec:
      containers:
      - image: docker.io/citizenstig/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 8000
      nodeSelector:
        node-role.kubernetes.io/worker: ''
