apiVersion: v1
kind: Service
metadata:
  name: httpbin-issue-1
  labels:
    app: httpbin-issue-1
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: httpbin-issue-1
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-issue-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-issue-1
      version: v1
  template:
    metadata:
      labels:
        app: httpbin-issue-1
        version: v1
    spec:
      containers:
      - image: docker.io/citizenstig/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        command: ["/bin/sh", "-c"]
        args: ["echo $(date); /run.sh"]
        ports:
        - containerPort: 8000
