apiVersion: v1
kind: Service
metadata:
  name: httpbin-issue-3
  labels:
    app: httpbin-issue-3
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: httpbin-issue-3
    version: v3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-issue-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-issue-3
      version: v3
  template:
    metadata:
      labels:
        app: httpbin-issue-3
        version: v3
    spec:
      containers:
      - image: docker.io/citizenstig/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
        ports:
        - containerPort: 8000
